version: '3.5'

services: 
    nginx:
        image: nginx
        container_name: nginx_server
        restart: always
    app:
        build: .
        working_dir: /var/www/react_bwd
        volumes: 
            - .:var/www/react_bwd
        command: [/bin/bash, ./docker/node/command.sh]